services:
  - docker

before_install:
  - docker build -t doc-build .
  - pip install -U pre-commit

install: true

script:
  - pre-commit run --all-files || exit 1
  - ./travis-validation.sh
  - ./docker-run.sh

# Deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: artifacts
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  repo: digitalliving/standards
  on:
    branch: master
